import type { Metadata } from "next";
import "./globals.css";
import { ModalProvider } from "./providers/model-provider";
import { ToastContainer } from "react-toastify";
import MainHeader from "./components/MainHeader";
import { getSession } from "./lib/actions";
import { verifyTokenEdge } from "./lib/jwt";
import { geistMono } from "./components/ui/Font";
import MainFooter from "./components/MainFooter";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  const sessionData = await verifyTokenEdge(session.token);

  return (
    <html lang="en">
      <body className={` ${geistMono.variable} antialiased`}>
        <MainHeader
          userSession={JSON.stringify(session)}
          sessionData={JSON.stringify(sessionData)}
        />
        {children}
        <MainFooter />
        <ToastContainer />
        <ModalProvider />
      </body>
    </html>
  );
}
