import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import "./globals.css";
import { ModalProvider } from "./providers/model-provider";
import { ToastContainer } from "react-toastify";
import MainHeader from "./components/MainHeader";
import { getSession } from "./lib/actions";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getSession();

  return (
    <html lang="en">
      <body
        className={` ${geistMono.variable} antialiased`}
      >
        <MainHeader userSession={JSON.stringify(session)} />
        {children}
        <ToastContainer />
        <ModalProvider />
      </body>
    </html>
  );
}
